# Generated by Django 2.1.4 on 2019-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populetic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='category',
            field=models.CharField(choices=[('Family', 'Family'), ('Love', 'Love'), ('Faith', 'Faith'), ('Hobbies', 'Hobbies'), ('Purpose', 'Purpose'), ('Engraving', 'Engraving')], default='none', max_length=5),
        ),
    ]
